{% set name = "pymyami" %}
{% set version = "2.0a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymyami-{{ version }}.tar.gz
  sha256: 2ad4eebab672487d49eadfac9e21dbeed953e4bc96fb0695102d64fea4636d16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - matplotlib-base
    - scikit-learn
    - scipy

test:
  imports:
    - pymyami
  # Looks for sklearn instead of scikit-learn.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/PalaeoCarb/MyAMI
  summary: MyAMI specific ion interaction model for calculating stoichiometric equilibrium constants in modified seawater.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
