{% set name = "pymyami" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymyami-{{ version }}.tar.gz
  sha256: ed0470b9dc54caa1857cb517bccf353997c3b30684de064ab35a552f71d315f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base
    - scikit-learn
    - scipy

test:
  imports:
    - pymyami
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PalaeoCarb/MyAMI
  summary: MyAMI specific ion interaction model for calculating stoichiometric equilibrium constants in modified seawater.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
